version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: 'JetbrainsSingleJRE/JetbrainsSingleJRE.csproj'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  github_token:
    secure: 2LiLyCv5qwnAClSid16P+Yiq+zIyBk+6/Xl1ZDOKz5g6ab2vXosiY3m93n52q1WX
build:
  project: JetbrainsSingleJRE.sln
  verbosity: minimal
artifacts:
- path: JetbrainsSingleJRE\bin\Release
  name: app
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: JetbrainsSingleJRE v$(appveyor_build_version)
  auth_token:
    secure: NQtMOO3yB309cDK/pFWRiQ==
  artifact: app
  on:
    branch: master
only_commits:
  files:
    - appveyor.yml
    - JetbrainsSingleJRE.sln
    - JetbrainsSingleJRE/JetbrainsSingleJRE.csproj
    - JetbrainsSingleJRE/**/*.cs
    - JetbrainsSingleJRE/**/*.resx
